Send link by share screen, copy link from QR code view
mayflower/PayForMe pull request #63
Opened 2023-05-23 19:08 UTC by nobbes

Added: share Link, copy Link in QR code view, translation
Update: dependencies, unit test
Remove: warnings, bugs :)

2023-05-24 15:10 UTC, Hustenbonbon commented
Hi, thanks for all the contribution, unfortunately currently I am very engaged in other projects and got little time to review and test all the small changes in detail.
If you plan to contribute more often, feel free to contact me on the mail in my github profile. We have a matrix chatroom with the developers of Cospend, iHateMoney, the Android and this app

2023-05-24 15:11 UTC, Hustenbonbon commented
Feel free to separate the localization, dispatchqueues and test-fixes in separate PRs, I can merge those right away

2023-05-24 15:54 UTC, nobbes commented
Thank you for your response, I will keep this in mind.

2025-05-03 21:58 UTC, InteractionEngineer requested changes
These changes are in conflict with the app publisher and irrelevant for the features mentioned in the PR. Please keep these kind of changes on you local machine.

2025-05-03 23:07 UTC, InteractionEngineer requested changes
**First of all: Thank you for your contribution** – I like the features you added to make it easier to share projects with others! Please look into the comments I left on each file modified. After the necessary changes where made, I'm happy to merge your PR and bring your feature to all current users.

2025-05-03 23:07 UTC, InteractionEngineer commented on PayForMeTests/AddProjectManuallyTests.swift
outdated but correct! …at this time already in the codebase

2026-05-10 23:38 UTC, closed without merging